### ISSUE TITLE
Move content from DatAgora repository AND wiki to this repository

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/DatAgoraWebSite#3]
The objective is to move the markdown content of [DatAgora wiki](https://github.com/VCityTeam/DatAgora/wiki) to this DatAgoraWebSite repository. But the images used by the [DatAgora wiki](https://github.com/VCityTeam/DatAgora/wiki) are in fact located in the [Pictures sub-directory of the DatAgora repository](https://github.com/VCityTeam/DatAgora/tree/master/Pictures) (as opposed to the DatAgora WIKI repository).

The task thus consists in 
  1. collecting to this repository the two sources of information
      - markdown content ([DatAgora wiki](https://github.com/VCityTeam/DatAgora/wiki)) on the one side and 
      - Pictures ([DatAgora/Pictures](https://github.com/VCityTeam/DatAgora/tree/master/Pictures)) on the other hand
  2. repairing the broken links so that DatAgoraWebSite becomes autonomous (does NOT refer to DatAgora repository anymore)
 
## First note 
The DatAgora repository has a single file ([RecognitionCity/Readme.md](https://github.com/VCityTeam/DatAgora/blob/master/RecognitionCity/Readme.md)) of pictures
```
git clone git@github.com:VCityTeam/DatAgora.git
cd DatAgora
grep -r Pictures *
```
Leave the two used pictures in the DatAgora website and, once the transfer of the other pictures is done, delete the others in order to avoid replications.

## Second note
Once the transfer of content of the [DatAgora wiki](https://github.com/VCityTeam/DatAgora/wiki) definitively [disable that wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis) at the github level.

**Comment by webanck** [comment]
Content has been tranfered.

Remaining tasks :
- investigate and fix potential dead links
- fix dead images (see https://projet.liris.cnrs.fr/vcity/DatAgora/fr/labxp_20/plantes.html for instance)
- disable the DatAgora wiki

**Comment by ggesquiere** [comment]
Please delete now the wiki part (with a possible texte to say that the website is on https://projet.liris.cnrs.fr/vcity/DatAgora/ 
Please move (after having archived the content) the https://github.com/VCityTeam/DatAgora that may seem to be quite similar to UD-SV page (en entry to components).

**Comment by webanck** [comment]
> Please delete now the wiki part (with a possible texte to say that the website is on https://projet.liris.cnrs.fr/vcity/DatAgora/

Could @ggesquiere or @EricBoix do it directly or give me the necessary rights to proceed ? I can't currently manage the DatAgora repository.

> Please move (after having archived the content) the https://github.com/VCityTeam/DatAgora that may seem to be quite similar to UD-SV page (en entry to components).

I don't understand this instruction. What are you speaking about, the readme page or the source code , can you please clarify ?

**Comment by webanck** [comment]
I just commited to remove the images that were still present in the DatAgora repo although these images will continue to live in the history of the repo.

**Comment by EricBoix** [comment]
@ggesquiere  Just to make sure and clarify things, and concerning the clean-up of the [project repository]( https://github.com/VCityTeam/DatAgora) what should be done is (following the [organization principles](https://github.com/VCityTeam/UD-SV/blob/master/ImplementationKnowHow/ProjectOrganizationalLogic/Readme.md))
 - [x] Move the [DataAgora/CityGML component ](https://github.com/VCityTeam/DatAgora/tree/master/CityGML) to a newly created DA-Something repository
  - [x] ditto with [Lego-city-counter](https://github.com/VCityTeam/DatAgora/tree/master/Lego-city-counter), [RecognitionCity](https://github.com/VCityTeam/DatAgora/tree/master/RecognitionCity), DashBoard, DataQuality
 - [x] clean-up the `Docs` sub-directory
 
Once the above done the DatAgora repository will persist in order to hold the project information (as opposed to code components and the [corporate/communication/for-deciders website](https://projet.liris.cnrs.fr/vcity/DatAgora/)

**Comment by ggesquiere** [comment]
@EricBoix @webanck @HomereB 
Sound good. 

- [x] The web site is now in https://github.com/VCityTeam/DatAgoraWebSite ; no need to keep the wiki part if all the part as be moved
- [x] Each component must have it own repository. If the component is now ready to consume or not mature, it may be push in a private repository.

**Comment by webanck** [comment]
To comment on the advancement of the resolution of this issue:

- [x] The [DatAgora wiki](https://github.com/VCityTeam/DatAgora/wiki) has been removed and now only redirects to the website.
- [x] The DatAgora code repository has been partially split in 3 components:
  * [UD-Legonizer](https://github.com/VCityTeam/UD-Legonizer)
  * [UD-CityGMLParser](https://github.com/VCityTeam/UD-CityGMLParser)
  * [UD-Mire](https://github.com/VCityTeam/UD-Mire)
- [x] 2 components not yet mature are still hidden in branches of the DatAgora code repo. As such, these components have been split in dedicated private repos: 
  * [DatAgora/Dashboard branch](https://github.com/VCityTeam/DatAgora/tree/Dashboard) moved to dedicated private repo [UD-Dashboard](https://github.com/VCityTeam/UD-Dashboard)
  * [DatAgora/DataQuality branch](https://github.com/VCityTeam/DatAgora/tree/DataQuality) moved to dedicated private repo [UD-DataQuality](https://github.com/VCityTeam/UD-DataQuality)
- [x] Clean up the `Docs` sub-directory: documents moved into [`DatAgora/Végétalisation` of the LIRIS NextCloud](https://partage.liris.cnrs.fr/index.php/apps/files/?dir=/DatAgora/V%C3%A9g%C3%A9talisation&fileid=251313553)
- [x] The links and images of the DatAgora website have not yet been fixed, but links checks have been added to Travis continuous integration.

**Comment by EricBoix** [comment]
Concerning the last item (DatAgoraWebsite), define (in .travi.syml) an [`after_deploy`](https://docs.travis-ci.com/user/job-lifecycle/) stage that checks the links of the (resulting) deployed website AND reports a failure when something is brain damaged ;-)

**Comment by ggesquiere** [comment]
The work seems to be done. Thanks for that. This may be closed once the components  are separated and the linked fixed.

**Comment by webanck** [comment]
I just created the repos of the remaining components (see edited message above) using the handy tool [git-filter-repo](https://github.com/VCityTeam/UD-SV/blob/master/Tools/ToolGit-Filter-Repo.md) to filter out the unnecessary history parts (about all other components) that were bloating the repos.

**Comment by webanck** [comment]
And it's finally over! For now anyway ;)
